name: React Native CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test React Native App
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - name: Lint Code
        run: npm run lint

      #   - name: Run Tests
      #     run: npm test
      #   - name: Set Gradlew Permissions
      #     run: chmod +x ./gradlew

      - name: Build Android APK
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-apk
          path: android/app/build/outputs/apk/release/*.apk
